-- Select statements to help the owner with the store problems 

-- How many orders are make by each employee
SELECT EMPLOYEE_STORE.FIRSTNAME, COUNT(ORDERS_STORE.ORDER#) AS NumberOfOrders FROM EMPLOYEE_STORE
INNER JOIN ORDERS_STORE ON ORDERS_STORE.EMPLOYEE# = EMPLOYEE_STORE.EMPLOYEE#
GROUP BY FIRSTNAME;

-- How long it take for each order to be delivered
SELECT ORDERS_STORE.ORDER#, (SHIPMENT_STORE.SHIPDATE - ORDERS_STORE.ORDERDATE) AS DAYTODELIVERY
FROM ORDERS_STORE,SHIPMENT_STORE 
WHERE ORDERS_STORE.SHIPMENTREF# = SHIPMENT_STORE.SHIPMENT#;

-- The profit of each product of the store
SELECT ITEM#, RETAIL - COST AS PROFIT
FROM ITEMS_STORE;

-- Total to pay of each order
SELECT ORDERS_STORE.ORDER#,SUM(ORDER_ITEMS_STORE.COSTEACH * ORDER_ITEMS_STORE.QUANTITY) AS TOTALPRICE FROM ORDERS_STORE
INNER JOIN ORDER_ITEMS_STORE ON ORDERS_STORE.ORDER# = ORDER_ITEMS_STORE.ORDERREF#
GROUP BY ORDER#
ORDER BY ORDER#;